### ISSUE TITLE
Error when using raiden-rs prelude

### ISSUE THREAD

**Issue by konradkonrad** [rakanalh/raiden.rs#73]
Hi @rakanalh, I hope you're doing well!

I tried using the `raiden-rs prelude` and I hit an error. See my example below:

```
cargo init --name check
cargo add raiden-rs

$ cat src/main.rs
use raiden-rs::prelude::*;
fn main() {
    println!("Hello, world!");
}
$ cat Cargo.toml
[package]
name = "check"
version = "0.1.0"
edition = "2021"

[dependencies]
raiden-rs = "0.1.0"
/tmp/check$ cargo build
   Compiling raiden-blockchain v0.1.0
error[E0432]: unresolved import `ecies::SecpError`
 --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/raiden-blockchain-0.1.0/src/keys.rs:3:9
  |
3 | pub use ecies::SecpError;
  |         ^^^^^^^^^^^^^^^^ no `SecpError` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `raiden-blockchain` (lib) due to 1 previous error
```

**Comment by rakanalh** [comment]
Hello @konradkonrad,

You're right. It seems like the library `ecies` removed the publicly imported `SecpError` in version [0.2.7](https://github.com/ecies/rs/blob/v0.2.7/src/lib.rs#L11) which is the version Cargo downloaded while it was there in version [0.2.6](https://github.com/ecies/rs/blob/v0.2.6/src/lib.rs#L10). Basically they broke backward compatibility with this change.

A quick solution to this would be to update your `Cargo.lock` file to downgrade `ecis` to 0.2.6. You might want to use `Cargo.lock` in this repository as a reference.

**Comment by rakanalh** [comment]
Tried fixing that in example you created:
```
cargo build
   Compiling raiden-check v0.1.0 (/home/rakan/Code/Rust/raiden-check)
warning: unused import: `raiden_rs::prelude::*`
 --> src/main.rs:1:5
  |
1 | use raiden_rs::prelude::*;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `raiden-check` (bin "raiden-check") generated 1 warning (run `cargo fix --bin "raiden-check"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

**Comment by konradkonrad** [comment]
Thanks, the workaround works here. I hope there are no security implications from using the old version. Looking at the [change set](https://github.com/ecies/rs/compare/v0.2.6...v0.2.7) nothing obvious springs to mind though.
